version: '3'

services:
  vhoarder-a:
    image: simiacode/video-hoarder:release-0.1.0-rc1
    container_name: video-hoarder
    restart: unless-stopped
    tty: false
    network_mode: bridge
    volumes:
      # This is where download queue and users etc. live.
      - /data/video-hoarder:/app/db-data
      # This is where we want our downloads to go.
      - /data/downloads/videos/:/app/download
      # WebApp settings; port, URL etc.
      - ./config.json:/app/config.json
    ports:
      # Should match settings in config.json.
      - 7200:7200
