version: "3"
services:
  app:
    depends_on:
      - db
    image: simiacode/video-hoarder:dev
    ports:
      - 8080:8080
    environment:
      PG_HOST: db
      PG_PORT: 5432
      PG_USER: postgres
      PG_PASSWORD: secretpassword
      DB_NAME: video-hoarder
      APP_HOST: mysubdomain.mydomain.com
      EXPOSED_PORT: 443
      APP_SCHEME: https
    volumes:
      - ~/Downloads:/workspace/downloads/admin
      - ./location.yml:/workspace/config/location.yml
  
  db:
    image: postgres:latest
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: secretpassword
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres

volumes:
  postgres-data:
